### ISSUE TITLE
feat: enable public api key for GraphQL queries 

### ISSUE THREAD

**Issue by matt-d-webb** [chess-centre/platform#242]
As a Guest User I want to see full events details
When navigating to a public landing page for an event
Then I see all entries, start date, end date, status of event

Example "public" event landing page: https://www.chesscentre.online/events/congress/2eea1210-dcd4-4237-8b08-b0721c1208dc

Currently both entries & member queries are authorised via cognito users for the graphQL API.

**Comment by adamelmore** [comment]
Closed by #265

**Comment by adamelmore** [comment]
Oh, I just read the body of the issue again and I guess there is outstanding frontend work here. Reopen if you'd like, @matt-d-webb!
