### ISSUE TITLE
feat: automation of game upload and publish.

### ISSUE THREAD

**Issue by matt-d-webb** [chess-centre/platform#243]
### Background

Our phyical venue has [Digital Chess Boards](http://www.digitalgametechnology.com/index.php/products/electronic-boards/usb) which record the moves of the games played, these are stored to a local micro server in [pgn format](https://en.wikipedia.org/wiki/Portable_Game_Notation) (<---example in wiki link).

During events there are upto 10 pgns per round generated with an average of 5 rounds per event totaling 50 pgns. As such we have a full list of games played by all players in an event, including the result of each game. This information we want to store against a users profile.

Player = Member.
Event = Entry = Player = Member.

**Useful Info:**

> As part of the official process for our events to be "rated", we manually submit the results of all our events to the ECF, here is an example event submitted:
> [The Chess Centre - ECF submitted event](https://www.ecfrating.org.uk/v2/new/list_games_swiss.php?event_code=LN00001396&section_no=1)
> 
> This means we can, if require query this unformation (by their ECF player ID) if required, example: 
> 
> https://www.ecfrating.org.uk/v2/new/api.php?v2/games/Rapid/player/225527/limit/100
> 
> This represents my (yep, Matt's) last ten published ECF games - this could be helpful as a means to avoid storing this same data ourselves.

### Objective

Store all pgn games for each player (member record) so that each logged in user can view their games via the [PGNViewer](https://github.com/chess-centre/platform/blob/master/chess-centre-app/src/components/ChessBoard/ChessBoard.js) 

On the Dashboard page you would see: count of games (associated to your memberId) / win & loss stats
On the game viewer page, see all games filtered by either: memberId or eventId 

![image](https://user-images.githubusercontent.com/36933715/128511478-81762626-a82c-4402-955a-ededddc103cb.png)

**Key questions:**

- How do we want to query these games? By MemberId (note there are two players for every game!), by EventId.
- Do we need to save all the event result data? Theoretically no, we can rely on the data submitted to the ECF as reference for each event and purely store game information and link to the ecf data associated to the game. This would potentially reduce duplicate admin for events.

**Comment by adamelmore** [comment]
@matt-d-webb I'm curious, does the ECF support digital upload of the PGN data such that we could automate that piece as well? Or will that have to be a manual step?

**Comment by matt-d-webb** [comment]
Sadly not. We would have to store this. If exposed an upload API, I would write a little node service that pushed the games up from the local micro server.

The manual effort would then be in the pairing data that the Digital Boards had so, at the beginning of an event we'd specify the players then the pairings. The software the digital boards use doesn't have an API only a GUI (painful). 

Here I can specify the membershipId which could be used to push the data to the upload API. 

I can take on this task of pushing the data.
