### ISSUE TITLE
feat: latest news feed

### ISSUE THREAD

**Issue by matt-d-webb** [chess-centre/platform#312]
As a User, when I log in
When I view the "latest news"
Then I see latest information & updates from our club

This feed should include the following:
- When new results are published
- When new ratings have been updated
- When new events have been added
- General club information updates

**Comment by matt-d-webb** [comment]
This is an opportunity to integrate a headless CMS. News shouldn't require a code deployment to populate or access to AWS backend configuration / services.

**Comment by akashsiddamshetty** [comment]
hello sir,
I would like to work on this issue can you guide me through it :smiley:

**Comment by matt-d-webb** [comment]
Hey @akashsiddamshetty, absolutely!

This is a significant feature and will require a lot of preparation on the backend. But this is something we can collaborate on together to complete the full ask.

I would propose splitting this into a number of parts:

1. **Newsfeed Item** - the component which will display the summarised information in the feed

This should take different forms (inject different templates) depending on the `newsType` it receives. For example: `results` or `general` or `ratings` where:

- **results** - a pre-defined template including final cross table of results and link to games
- **general** - a format that could potentially be expanded out to a CMS, and render markdown - [suggestion](https://www.youtube.com/watch?v=J0Wy359NJPM)
- **ratings** - a pre-defined template that takes in the published, scheduled rating changes

Here is a quick mock of what I mean by "newsTypes":

![image](https://user-images.githubusercontent.com/36933715/149662777-db9a86c7-348a-42b1-9fc5-f5e33c8212be.png)

Initially, just providing a basic structure to the item would be sufficient: `header`, `title`, `body`, `footer` - accounting for responsible design.

Here is a great tool to quickly scaffold the Newsfeed Item: https://play.tailwindcss.com/



2. **Newsfeed View**

Providing a dynamic feed of news items, this can then be toggled to view by type, including from the URL so other views in the application can navigate both to the individual item `/app/feed?item=230498234` or just to a type `/app/feed?type=general`

These cover the key first parts for the frontend. Below is what I initially propose for the data structure:

```ts
interface NewsFeedItem {
  id: string,
  type: NewsFeedType,
  title: string,
  body: string, // <--- need understand how we parse the HTML / markdown
  createAt: date,
  visible: boolean
}

interface NewsFeedType {
   id: string,
   name: ["rating" | "general" | "result"],
   resultId: string | null, // <-- helper reference to open any detailed view of results
   eventId: string | null, // <--- helper reference to open any detailed event view (such as announced events!)
}
```
I will have no doubt missed something here, like images, but this gives some initial thoughts.
