### ISSUE TITLE
fix: game history chart blank months

### ISSUE THREAD

**Issue by matt-d-webb** [chess-centre/platform#446]
Currently, the games history bar chart will only display information for the months you have played games:

![image](https://user-images.githubusercontent.com/36933715/147010680-59d79173-cca1-45b9-9ffb-0e296bb785df.png)

Looks to be here, the iteration is purely based on games rather than array of months [1, n]:

```js
function genGameHistory(games) {
  // This structures the data so it can be passed to the users dashboard:
  return games.reduce((prev, { date, type }) => {
    const month = date ? new Date(date).toLocaleString('default', { month: 'long' }) : '';
    const exists = prev.find(g => g.month === month);
    if (exists) {
      const index = prev.findIndex(g => g.month === month);
      prev[index][type] ? prev[index][type] += 1 : prev[index][type] = 1;
      return [...prev];
    } else {
      return [...prev, {
        month,
        [type]: 1
      }];
    }
  }, []);
}
```

Ref: https://github.com/chess-centre/platform/blob/master/chess-centre-app/amplify/backend/function/updateGameHistory/src/getGameInfo.js#L50

**Comment by sunnyjain15699** [comment]
Hi! I would like to work on this issue. Can you guide me through it ?

**Comment by matt-d-webb** [comment]
Hi @sunnyjain15699 

Of course, since raising this, I realise we can 'fix' this in two ways, the second option being by handling the data in the client rather than changing the lambda function. Either would be fine to achieve the desired result.

**Key files:**
Client Chart Data Function
https://github.com/chess-centre/platform/blob/master/chess-centre-app/src/api/data.dashboard.js#L98

**Client Component:**
https://github.com/chess-centre/platform/blob/master/chess-centre-app/src/pages/App/Dashboard.js#L196

Here is a sample of the "game info" response:
```
{
  stats: { wins: 4, whiteWins: 4, draws: 1, losses: 6, blackWins: 0 },
  history: [
    { standard: 1, month: "July", rapid: 5 },
    { month: "June", rapid: 5 },
  ],
};
```

We would expect:
```
{
  stats: { wins: 4, whiteWins: 4, draws: 1, losses: 6, blackWins: 0 },
  history: [
    { standard: 0, month: "October", rapid: 0 },       // <---- blank record --- //
    { standard: 0, month: "September", rapid: 0 },  // <---- blank record --- //
    { standard: 0, month: "August", rapid: 0 },        // <---- blank record --- //
    { standard: 1, month: "July", rapid: 5 },
    { month: "June", rapid: 5 },
  ],
};
```

This would result in a clearer reflection of games played over a 6 months period:
![image](https://user-images.githubusercontent.com/36933715/147494545-0de34fed-06ae-40df-8767-80d0e02a9140.png)

**Comment by matt-d-webb** [comment]
@sunnyjain15699 hey, are you still looking to pick this up? If not, I will pick it up. 😀

**Comment by matt-d-webb** [comment]
Fixed
![image](https://user-images.githubusercontent.com/36933715/160727884-c57f22b1-e5b5-474a-87d1-15afd564cdfc.png)
